force-app/main/default/objects/Audit_Log__c/Audit_Log__c.object-meta.xml
<CustomObject>
    <label>Audit Log</label>
    <nameField>
        <displayFormat>AL-{00000000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Log__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex Class</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Custom Apps</fullName>
            </value>
            <value>
                <fullName>Customize Accounts</fullName>
            </value>
            <value>
                <fullName>Customize Campaigns</fullName>
            </value>
            <value>
                <fullName>Customize Contacts</fullName>
            </value>
            <value>
                <fullName>Customize Leads</fullName>
            </value>
            <value>
                <fullName>Customize Users</fullName>
            </value>
            <value>
                <fullName>Custom Objects</fullName>
            </value>
            <value>
                <fullName>Field Restriction Rule</fullName>
            </value>
            <value>
                <fullName>Flows</fullName>
            </value>
            <value>
                <fullName>Lightning Components</fullName>
            </value>
            <value>
                <fullName>Lightning Pages</fullName>
            </value>
            <value>
                <fullName>Manage Users</fullName>
            </value>
            <value>
                <fullName>Matching Rule</fullName>
            </value>
            <value>
                <fullName>Page</fullName>
            </value>
            <value>
                <fullName>Security Controls</fullName>
            </value>
            <value>
                <fullName>Sharing Defaults</fullName>
            </value>
            <value>
                <fullName>Sharing Rules</fullName>
            </value>
            <value>
                <fullName>Static Resource</fullName>
            </value>
            <value>
                <fullName>Track Field History</fullName>
            </value>
            <value>
                <fullName>Workflow Rule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit_Log__c/fields/Source_Namespace_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Source_Namespace_Prefix__c</fullName>
    <label>Source Namespace Prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Rule__c/Audit_Rule__c.object-meta.xml
<CustomObject>
    <label>Audit Rule</label>
    <nameField>
        <displayFormat>AR-{00000000}</displayFormat>
        <label>Rule Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Rule__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <label>Condition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>equals</fullName>
            </value>
            <value>
                <fullName>does not equal</fullName>
            </value>
            <value>
                <fullName>starts with</fullName>
            </value>
            <value>
                <fullName>catch all</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit_Rule__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Namespace</fullName>
            </value>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Section</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit_Rule__c/fields/Permission__c.field-meta.xml
<CustomField>
    <fullName>Permission__c</fullName>
    <label>Permission</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allow</fullName>
            </value>
            <value>
                <fullName>Deny</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Audit_Rule__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <externalId>true</externalId>
    <label>Sequence</label>
    <precision>7</precision>
    <required>true</required>
    <scale>3</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Rule_Processor.cls
public with sharing class Rule_Processor
{
	// ************************************************
	// usage:
	//		Rule_Processor.Permission perm = Rule_Processor.getRP().checkLog(my_Audit_Log_record);
	//		if (perm == Rule_Processor.Permission.ALLOW)
	//		if (perm == Rule_Processor.Permission.DENY)





	// ************************************************
	// *** Member vars
	public enum Permission {ALLOW, DENY}

	private List<Audit_Rule__c> rules;
	private static Rule_Processor RP;

	private static Map<String, String> fieldMap = new Map<String,String> // Rule field => Log API field name
	{
		'User'      => 'User__c',
		'Namespace' => 'Source_Namespace_Prefix__c',
		'Action'    => 'Action__c',
		'Section'   => 'Section__c'
	};


	// ************************************************
	// *** Constructor
	public Rule_Processor()
	{
		loadRules();
	}


	// ************************************************
	// *** Static methods
	public static Rule_Processor getRP()
	{
		if (RP == null) RP = new Rule_Processor();
		return RP;
	}


	// ************************************************
	// *** Instance methods
	private void loadRules()
	{
		rules = [SELECT Id, Name, Sequence__c, Field__c, Condition__c, Value__c, Permission__c FROM Audit_Rule__c ORDER BY Sequence__c ASC];
	}

	public Permission checkLog(Audit_Log__c AL)
	{
		String output;

		for (Audit_Rule__c rule: rules)
		{
			String ruleField = rule.Field__c;
			String ruleCond  = rule.Condition__c;
			String ruleValue = rule.Value__c;
			String rulePerm  = rule.Permission__c;

			if (ruleCond != null && ruleCond == 'catch all')
			{
				// apply catch all, break;
				output = ruleValue;
				break;
			}

			if (ruleField == null || ruleCond == null || ruleValue == null || rulePerm == null)
			{
				// big error
				System.debug(System.LoggingLevel.ERROR, 'Fatal error: Rule invalid. Cannot continue.');
				return null;
			}

			String logField = fieldMap.get(ruleField);
			String logValue;

			if (AL.get(logField) != null) logValue = (String)AL.get(logField);

			switch on ruleCond
			{
				when 'equals'
				{
					if (logValue == ruleValue)
					{
						output = rulePerm;
						break;
					}
				}

				when 'does not equal'
				{
					if (logValue != ruleValue)
					{
						output = rulePerm;
						break;
					}
				}

				when 'starts with'
				{
					if (logValue.startsWith(ruleValue))
					{
						output = rulePerm;
						break;
					}
				}

				when else
				{
					// big error
					System.debug(System.LoggingLevel.ERROR, 'Error: Rule invalid. Attempting to continue.');
					continue;
				}
			}
		}

		// maybe we have an output now?
		return getPermEnum(output);
	}

	public Permission getPermEnum(String strPerm)
	{
		if (strPerm == null) 
		{
			System.debug('getPermEnum is null.');
			return null;
		}

		if (strPerm == 'Allow') return Permission.ALLOW;
		if (strPerm == 'Deny') return Permission.DENY;
		return null;
	}
}